### ISSUE TITLE
Check file format in assets before generating keys

### ISSUE THREAD

**Issue by xzhorikx** [Jesway/Flutter-Translate-Gen#3]
Hi!

I was following your instructions on how to generate statically typed localization keys, but I encountered following issue: 

When running `flutter pub run build_runner build --delete-conflicting-outputs` I received the following output
```
SEVERE] flutter_translate_gen:static_keys_generator on lib/presenter/localization/keys.dart:
Error running FlutterTranslateGen
Ths JSON format is invalid.
```

I had 2 json files in `assets/i18n` that were valid according to multiple JSON validators online and IDE, so I started to investigate further and realized that `assets` variable in `FlutterTranslateGen.getKeyMap()` function also includes hidden files in  `assets/i18n` which cannot be parsed with `json.decode(await step.readAsString(entity));` and thus throw an exception.

In my case I had a macOS's default `.DS_store` metadata file in a  `assets/i18n` folder and `FlutterTranslateGen` tried to parse it from JSON.

Suggestions:
* Make check for file format in `FlutterTranslateGen.getKeyMap()`
* If not possible, provide a bit more information in exception, such as file name/path instead of current `throw InvalidGenerationSourceError("Ths JSON format is invalid.");`

**Comment by bratan** [comment]
@xzhorikx - Thanks for reporting this issue, I will take a look at it.

**Comment by bratan** [comment]
I've updated the example so the build considers only json files https://github.com/Jesway/Flutter-Translate-Gen/commit/cbd10d639cba0872daf2d6f4ec552f2a2f31d93e
